### ISSUE TITLE
Toolbar not styled in Fullscreen

### ISSUE THREAD

**Issue by unseen-ninja** [denis-g/theme-forklift4-catppuccin#1]
Heya, just chiming in real quick – this may be a Forklift issue, but I've noticed that the toolbar isn't styled when the app is in fullscreen. For Latte it isn't really that noticable, but for the dark variants it's a little … *meh*.

Is there a workaround for that by any chance?

<img width="1306" alt="image" src="https://github.com/denis-g/theme-forklift4-catppuccin/assets/35840154/3d1bee6c-2d4d-4af8-a76d-d68ea8127c11">

**Comment by denis-g** [comment]
Yo,
This is a Forklift interface bug. No separate settings for normal/fullscreen.
Maybe it will be fixed on the next release ... or send them feedback on this and maybe they will fix it even faster.

**Comment by unseen-ninja** [comment]
How annoying.. I'll send in some feedback, and hopefully they get around to fixing it. Would love to use a custom theme for forklift – but I have it fulscreened pretty much all the time. ,_,
